### ISSUE TITLE
Add an option to return raw yaml

### ISSUE THREAD

**Issue by leesei** [vfile/vfile-matter#5]
### Initial checklist

- [X] I read the [support docs](https://github.com/vfile/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/vfile/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/vfile/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Avfile&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I am using vfile-matter for frontmatter processing.
I would like to check if there is any change to the frontmatter before writing to the file (like the dimmed file name of prettier).
So I need the raw yaml for comparison.

### Solution

I think that we can add a `matched: boolean` to `Options`.
Set `file.data.matter_matched = match` if requested, `null` otherwise.

### Alternatives

Always return matched?
Return raw yaml?

**Comment by wooorm** [comment]
hi!
I don’t understand how this feature helps your goal?
Perhaps you can expand on your actual problem some more?

I’d think you want to check if the entire file is changed or not. For that, I would hash the original file, and hash the current file, when those differ the file is changed.

```js
import crypto from 'node:crypto'

const before = crypto.createHash('md5').update(String(originalFile)).digest('hex')
const after = crypto.createHash('md5').update(String(newFile)).digest('hex')
const changed = after !== before
```

**Comment by leesei** [comment]
Here's how I would like to use it:

```ts
matter(vfile, { strip: true });
// I do sorting and transform of frontmatter here
vfile.data.matter = normalize_frontmatter(frontmatter);

// if I have the source yaml as string
// I can do something like (stripping and edge cases aside)
// file.data.should_write = (vfile.data.yaml_raw == yaml.stringify(vfile.data.matter));

// writing file
await writeFile(
  out_path,
  "---\n" +
    yaml.stringify(vfile.data.matter) +
    "---\n" +
    vfile.toString()
);
```

You suggestion would work, but:
- it requires reading `originalFile` again
- it requires writing out the `newFile` for comparison

Frankly speaking I've yet to study how it's done in Prettier and my thought might be a premature optimization :stuck_out_tongue: .

Again, since `vfile-matter` is just a small library I could have just forked it and use my fork in my project.
Just wondering if my use case makes sense to be merged upstream.

**Comment by wooorm** [comment]
> it requires reading originalFile again

I don’t think it does. The file you have when you call `matter`, is the original file. Which you can pass here.

> it requires writing out the newFile for comparison

I don’t think it does. You can do that when `changed` is `true`, in which case it is changed.

>  I've yet to study how it's done in Prettier 

I am pretty sure that it is done the way I propose. I can’t see how else it would work.

**Comment by leesei** [comment]
> The file you have when you call `matter`, is the original file. Which you can pass here.

Since I called `matter(vfile, { strip: true })`, the YAML header is stripped.
If I don't use `strip`, I would have to search and replace the YAML on my own.
This why I thought of returning `match` in the first place.

What I meant is the construction of file in memory, not writing it out. 
Indeed your example can be done in memory and not involving file I/O (except for the aforementioned issue that I don't have the original YAML or whole file).
Since I'm only modifying the frontmatter it seems more strict forward and efficient to just compare the YAML.

**Comment by wooorm** [comment]
I really don‘t understand what you want apparently?

Why doesn’t your `normalize_frontmatter` track whether it changes things?
Why don’t you diff objects?

```
matter(vfile, { strip: true });
const nextMatter = normalize_frontmatter(frontmatter);

if (someDiffFunction(vfile.data.matter, nextMatter) {
  // Write
}
```

I don’t understand where prettier works on frontmatter but ignores the rest of the file?

Why do you even *want* to diff? It’s probably fine to just write the file?

**Comment by leesei** [comment]
Diffing the JavaScript object parsed from frontmatter doesn't work:

Input:
```
tags: ["github"]
```

Formatted:
```
tags:
  - github
```

These two correspond to the same JS object.
It is my requirement to only work on the frontmatter, not Prettier's.
Prettier doesn't format the frontmatter so I'm writing my own.

Yes, as I memtioned before, it's probably just fine to overwrite the files irregardless of whether there's a change or not.

**Comment by wooorm** [comment]
> It is my requirement to only work on the frontmatter, not Prettier's.

Why is it that you only care about frontmatter?
Most of the times, our tools are about the AST. VFile was specifically made to work alongside those.
That doesn’t mean it’s the only use case for it, but it remains the primary focus.

What does Prettier have to do with all this? Are you making a prettier plugin?

**Comment by leesei** [comment]
Noted that the goal of this library is not for frontmatter processing.
Closing this issue.
